export { default as Hero } from './Hero';
export { default as Marquee } from './Marquee';
export { default as Manifesto, default as Philosophy } from './Manifesto';
export { default as Skiper39, CrowdCanvas } from './CrowdCanvas';
export { default as TwoPaths } from './TwoPaths';
export { default as Services } from './Services';
export { default as DigitalMarketingPreview } from './DigitalMarketingPreview';
export { default as SelectedWork } from './SelectedWork';
export { default as WhyKodewar } from './WhyKodewar';
export { default as CareersPreview } from './CareersPreview';
export { default as Workspace } from './Workspace';
export { default as TechStack, default as Technology } from './TechStack';
export { default as HowWeWork, default as Process } from './HowWeWork';
export { default as Awards, default as Recognition } from './Awards';
export { default as Clients } from './Clients';
export { default as Reviews, default as Testimonials } from './Reviews';
export { default as Team } from './Team';
export { default as Studio } from './Studio';
export { default as ContactCTA } from './ContactCTA';
export { default as FAQ } from './FAQ';
