-- ==============================================================
-- KODEWAR TALENT — POSTGRESQL / SUPABASE SEED MIGRATION
-- Generated At: 2026-10-02T11:02:00.769Z
-- Strategy: Idempotent INSERT ... ON CONFLICT (id) DO NOTHING
-- Safe: Never overwrites or deletes existing production records
-- ==============================================================
BEGIN;

-- 1. USERS
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('admin_kodewar_default_01', 'KODEWAR Admin', 'admin@kodewar.com', '$2b$10$I7PsASZZXL5zwSMrjuPDze93JzuRYVooG0/5915BJbKtsMSn5T3Cu', 'ADMIN', 'local', NULL, NULL, '2026-10-02T05:44:17.906Z', '2026-10-02T10:59:01.119Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790919858050_5pun4', 'Candidate', 'test.candidate.1790919857750@kodewar.test', '$2b$10$JPLdGyUrbwjjl0L5/BymF.4xQxHdzLt/OyEhPAs/Mr5jgmrOWU0MC', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T05:44:18.051Z', '2026-10-02T05:44:18.051Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790919940279_ijgx5', 'Candidate', 'test.candidate.1790919940126@kodewar.test', '$2b$10$uCp3//Ryy30I2rP6VzmIKulfSoX9dDqmJU/lF/74b.v1Ji1i9GSBu', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T05:45:40.279Z', '2026-10-02T05:45:40.279Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790919954871_2obaz', 'Candidate', 'test.candidate.1790919954755@kodewar.test', '$2b$10$9USa0QbVDBQu0Q/piJjBMuA218yzZBfPhs5nAGkuLTF5rJaQ5VLqi', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T05:45:54.871Z', '2026-10-02T05:45:54.871Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790922077090_ibz73', 'Candidate', 'candidate.one.1790922077007@kodewar.test', '$2b$10$QQ0r.NLIvFVqLFpxf4Ydyuz710TyS081Qp6Gh2kT2jX2vfFxmArtC', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T06:21:17.091Z', '2026-10-02T06:21:17.091Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790922077176_mlhvt', 'Candidate', 'candidate.two.1790922077094@kodewar.test', '$2b$10$mA5yKSVzGEqxrDGZ6ytY5uxnRvx7pID8x36giP8nWMAOPU6EUnGZO', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T06:21:17.177Z', '2026-10-02T06:21:17.177Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790922188633_9si1j', 'Candidate', 'candidate.one.1790922188548@kodewar.test', '$2b$10$vPSgt8rUUz.lu9asP7JLju389xIW/Go7lO5AkzQk.xgqICQuQ9eze', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T06:23:08.634Z', '2026-10-02T06:23:08.634Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790922188726_p99l0', 'Candidate', 'candidate.two.1790922188637@kodewar.test', '$2b$10$3N1hOrgRkBlAL7tMw5S5qeHbDO0YaA0gY/mI1BT5BKYyi2sYRCosu', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T06:23:08.726Z', '2026-10-02T06:23:08.726Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790924349971_3vivx', 'Candidate', 'hardening.candidate.1790924349748@kodewar.test', '$2b$10$Rg9E6Ri0SlH3sHnkW/EvXuCxgV0IizywsoGiX7slZbveuHLEP2/Ei', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T06:59:09.972Z', '2026-10-02T06:59:09.972Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790924726791_bswno', 'Candidate', 'candidate.one.1790924726630@kodewar.test', '$2b$10$Sa2l4cxq2MvJaDwTRjTff.i0JsMmVfwsWVfrfaYioRrK3orhE.rsy', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T07:05:26.792Z', '2026-10-02T07:05:26.792Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790924726991_hge6j', 'Candidate', 'candidate.two.1790924726802@kodewar.test', '$2b$10$H7pzVgISJkkiMQ2dwFTYpOLgc4y50dm9v8qxVghAI9GBpEwi6N8ES', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T07:05:26.993Z', '2026-10-02T07:05:26.993Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790924871492_420yo', 'Candidate', 'test.candidate.1790924871387@kodewar.test', '$2b$10$6wOcfBwqZiN2p6vZevRq8ue6iQVoZlkhUb3oJNufrFtwH8TI6Rezq', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T07:07:51.493Z', '2026-10-02T07:07:51.493Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790938741082_nge5g', 'Candidate', 'hardening.candidate.1790938740886@kodewar.test', '$2b$10$ZchbyRrEeJKiNKHdAekw1u3QuEEUbneT9zptgXUicQOPyYOQCDsG.', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T10:59:01.082Z', '2026-10-02T10:59:01.082Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790938775308_dsjtp', 'Candidate', 'candidate.one.1790938775024@kodewar.test', '$2b$10$RWTs1Qb4VLp7hUobv9DXzOr8N064s0wY9QVjfpAGb90b.6Y6gl.YG', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T10:59:35.309Z', '2026-10-02T10:59:35.309Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790938775652_sq0x3', 'Candidate', 'candidate.two.1790938775321@kodewar.test', '$2b$10$XBqmtYz60okdo/dTpRZPz.l60KmyKk9uCTJGs1M3vpyVbRsR9IG6u', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T10:59:35.652Z', '2026-10-02T10:59:35.652Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, auth_provider, google_sub, avatar_url, created_at, updated_at) VALUES ('usr_1790938792342_cnrug', 'Candidate', 'test.candidate.1790938791987@kodewar.test', '$2b$10$h6ljZcM10DpgZRRu7xUF/efUj.kaLzhtfuHIH/gGl8IIheWemsWjK', 'CANDIDATE', 'local', NULL, NULL, '2026-10-02T10:59:52.343Z', '2026-10-02T10:59:52.343Z') ON CONFLICT (id) DO NOTHING;

-- 2. CANDIDATE PROFILES
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790919858053', 'usr_1790919858050_5pun4', 'Harsha Vardhan', 'test.candidate.1790919857750@kodewar.test', '+91 9876543210', 'Hyderabad, India', 'JNTU Hyderabad', 'B.Tech Computer Science', '', '2025', 'React, Node.js, TypeScript, Next.js, CSS3', '', 'Associate Frontend Developer Intern', '', '', '', 'C:\Users\bantu\Desktop\KWT\backend\uploads\resumes\resume_Harsha_Resume_2026_1790919858081-627133.pdf', 'Harsha_Resume_2026.pdf', 65, '2026-10-02T05:44:18.090Z', '2026-10-02T05:44:18.053Z', '2026-10-02T05:44:18.090Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790919940280', 'usr_1790919940279_ijgx5', 'Harsha Vardhan', 'test.candidate.1790919940126@kodewar.test', '+91 9876543210', 'Hyderabad, India', 'JNTU Hyderabad', 'B.Tech Computer Science', '', '2025', 'React, Node.js, TypeScript, Next.js, CSS3', '', 'Associate Frontend Developer Intern', 'https://linkedin.com/in/harsha', 'https://github.com/harshavardhan', 'https://harsha.dev', 'C:\Users\bantu\Desktop\KWT\backend\uploads\resumes\resume_Harsha_Resume_2026_1790919940303-386237.pdf', 'Harsha_Resume_2026.pdf', 65, '2026-10-02T05:45:40.312Z', '2026-10-02T05:45:40.281Z', '2026-10-02T05:45:40.321Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790919954873', 'usr_1790919954871_2obaz', 'Harsha Vardhan', 'test.candidate.1790919954755@kodewar.test', '+91 9876543210', 'Hyderabad, India', 'JNTU Hyderabad', 'B.Tech Computer Science', '', '2025', 'React, Node.js, TypeScript, Next.js, CSS3', '', 'Associate Frontend Developer Intern', 'https://linkedin.com/in/harsha', 'https://github.com/harshavardhan', 'https://harsha.dev', 'C:\Users\bantu\Desktop\KWT\backend\uploads\resumes\resume_Harsha_Resume_2026_1790919954886-714571.pdf', 'Harsha_Resume_2026.pdf', 65, '2026-10-02T05:45:54.888Z', '2026-10-02T05:45:54.873Z', '2026-10-02T05:45:54.896Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790922077092', 'usr_1790922077090_ibz73', 'Ananya Sharma', 'candidate.one.1790922077007@kodewar.test', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T06:21:17.092Z', '2026-10-02T06:21:17.092Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790922077178', 'usr_1790922077176_mlhvt', 'Vikram Reddy', 'candidate.two.1790922077094@kodewar.test', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T06:21:17.178Z', '2026-10-02T06:21:17.178Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790922188634', 'usr_1790922188633_9si1j', 'Ananya Sharma', 'candidate.one.1790922188548@kodewar.test', '+91 9988776655', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T06:23:08.635Z', '2026-10-02T06:23:08.747Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790922188727', 'usr_1790922188726_p99l0', 'Vikram Reddy', 'candidate.two.1790922188637@kodewar.test', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T06:23:08.728Z', '2026-10-02T06:23:08.728Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790924349973', 'usr_1790924349971_3vivx', 'Hardening Test Candidate', 'hardening.candidate.1790924349748@kodewar.test', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T06:59:09.974Z', '2026-10-02T06:59:09.974Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790924726795', 'usr_1790924726791_bswno', 'Ananya Sharma', 'candidate.one.1790924726630@kodewar.test', '+91 9988776655', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T07:05:26.796Z', '2026-10-02T07:05:27.044Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790924726996', 'usr_1790924726991_hge6j', 'Vikram Reddy', 'candidate.two.1790924726802@kodewar.test', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T07:05:26.997Z', '2026-10-02T07:05:26.997Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790924871496', 'usr_1790924871492_420yo', 'Harsha Vardhan', 'test.candidate.1790924871387@kodewar.test', '+91 9876543210', 'Hyderabad, India', 'JNTU Hyderabad', 'B.Tech Computer Science', '', '2025', 'React, Node.js, TypeScript, Next.js, CSS3', '', 'Associate Frontend Developer Intern', 'https://linkedin.com/in/harsha', 'https://github.com/harshavardhan', 'https://harsha.dev', 'C:\Users\bantu\Desktop\KWT\backend\uploads\resumes\resume_Harsha_Resume_2026_1790924871531-243499.pdf', 'Harsha_Resume_2026.pdf', 65, '2026-10-02T07:07:51.541Z', '2026-10-02T07:07:51.497Z', '2026-10-02T07:07:51.552Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790938741084_k85cc', 'usr_1790938741082_nge5g', 'Hardening Test Candidate', 'hardening.candidate.1790938740886@kodewar.test', '+91 9999988888', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T10:59:01.084Z', '2026-10-02T10:59:01.084Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790938775313_jwxtc', 'usr_1790938775308_dsjtp', 'Ananya Sharma', 'candidate.one.1790938775024@kodewar.test', '+91 9988776655', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T10:59:35.313Z', '2026-10-02T10:59:35.707Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790938775655_j8liq', 'usr_1790938775652_sq0x3', 'Vikram Reddy', 'candidate.two.1790938775321@kodewar.test', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, NULL, '2026-10-02T10:59:35.655Z', '2026-10-02T10:59:35.655Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidate_profiles (id, user_id, full_name, email, phone, location, college, degree, field, graduation_year, skills, experience, current_role, linkedin, github, portfolio, resume_storage_path, resume_filename, resume_size, resume_uploaded_at, created_at, updated_at) VALUES ('prof_1790938792346_zbcit', 'usr_1790938792342_cnrug', 'Harsha Vardhan', 'test.candidate.1790938791987@kodewar.test', '+91 9876543210', 'Hyderabad, India', 'JNTU Hyderabad', 'B.Tech Computer Science', '', '2025', 'React, Node.js, TypeScript, Next.js, CSS3', '', 'Associate Frontend Developer Intern', 'https://linkedin.com/in/harsha', 'https://github.com/harshavardhan', 'https://harsha.dev', 'C:\Users\bantu\Desktop\KWT\backend\uploads\resumes\resume_Harsha_Resume_2026_1790938792396-678722.pdf', 'Harsha_Resume_2026.pdf', 65, '2026-10-02T10:59:52.461Z', '2026-10-02T10:59:52.346Z', '2026-10-02T10:59:52.475Z') ON CONFLICT (id) DO NOTHING;

-- 3. JOBS
INSERT INTO jobs (id, title, department, employment_type, workplace_type, location, experience_level, salary_range, featured, skills, summary, about_role, responsibilities, requirements, benefits, deadline, status, created_at, updated_at) VALUES ('frontend-engineer-react', 'Frontend Engineer (React / Next.js)', 'Software Development', 'Full-time', 'Hybrid', 'Hyderabad / Remote', '1–3 Years', '₹6,00,000 – ₹10,00,000 / year', TRUE, 'React, Next.js, TypeScript, Tailwind CSS, GSAP', 'Architect high-performance web applications, fluid micro-interactions, and enterprise design systems with sub-second page performance.', 'As a Frontend Engineer at KODEWAR, you will build user-facing platforms for global clients and internal products. You will work closely with product designers to translate Figma design tokens into clean, performant React components.', 'Build responsive, production-ready user interfaces using React, Next.js, and TypeScript.
Implement fluid animations and micro-interactions utilizing GSAP and CSS transforms.
Collaborate with UI/UX designers to translate Figma tokens into scalable component libraries.
Optimize web applications for peak Core Web Vitals and accessibility standards.', 'Proficiency in React, modern JavaScript (ES6+), and CSS/Tailwind.
Experience with state management, asynchronous data fetching, and RESTful APIs.
Strong eye for spacing, typography, and micro-interactions.
Portfolio or GitHub repositories demonstrating real deployed projects.', 'Work on live production platforms across multiple continents.
Direct 1-on-1 code reviews and architectural mentorship.
High-velocity shipping culture without bureaucratic friction.
Continuous hardware and learning stipend support.', '2026-12-31', 'PUBLISHED', '2026-10-02T06:14:11.304Z', '2026-10-02T06:14:11.304Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO jobs (id, title, department, employment_type, workplace_type, location, experience_level, salary_range, featured, skills, summary, about_role, responsibilities, requirements, benefits, deadline, status, created_at, updated_at) VALUES ('fullstack-developer-mern', 'Full Stack Developer (Node.js & React)', 'Software Development', 'Full-time', 'In-Studio', 'Hyderabad', '2–4 Years', '₹8,00,000 – ₹14,00,000 / year', TRUE, 'Node.js, Express, React, PostgreSQL, REST APIs', 'Lead end-to-end development of client-facing platforms, secure API microservices, and robust relational data pipelines.', 'Join our core platform engineering team in Madhapur, Hyderabad. You will architect resilient backend services, design optimized database schemas, and deliver polished web interfaces.', 'Design, develop, and maintain resilient Node.js / Express microservices and REST APIs.
Architect relational database schemas in PostgreSQL / MySQL with optimized indexing.
Integrate third-party payment gateways, authentication providers, and webhooks.
Participate in agile sprint ceremonies, peer code reviews, and architecture spikes.', 'Demonstrated experience building and maintaining full-stack web applications.
Strong grasp of backend architectural patterns, JWT authentication, and database modeling.
Familiarity with containerization (Docker) and cloud deployments.', 'Direct ownership of entire product features from inception to deployment.
Collaborative engineering squad alongside experienced leads.
Merit-driven compensation and accelerated career progression.
Studio workplace in Madhapur, Hyderabad with hybrid flexibility.', '2026-12-31', 'PUBLISHED', '2026-10-02T06:14:11.304Z', '2026-10-02T06:14:11.304Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO jobs (id, title, department, employment_type, workplace_type, location, experience_level, salary_range, featured, skills, summary, about_role, responsibilities, requirements, benefits, deadline, status, created_at, updated_at) VALUES ('ui-ux-product-designer', 'UI/UX Product Designer', 'UI/UX & Design', 'Full-time', 'Hybrid', 'Hyderabad / Remote', '2–4 Years', '₹6,50,000 – ₹11,00,000 / year', TRUE, 'Figma, Design Systems, Wireframing, UX Research, Micro-interactions', 'Craft high-conversion product interfaces, interactive design tokens, and user research archetypes for complex digital ecosystems.', 'Work at the intersection of aesthetic craft and usability. You will lead interface architecture across web, mobile, and SaaS dashboards.', 'Translate ambiguous client requirements into clear wireframes, user journeys, and mockups.
Maintain and evolve the KODEWAR design system and component tokens in Figma.
Conduct usability audits, prototype micro-interactions, and hand off specifications to frontend engineers.
Iterate based on qualitative client feedback and quantitative product telemetry.', 'High-caliber portfolio showcasing shipped web apps, mobile apps, or design systems.
Mastery of Figma, Auto-layout, component variants, and interactive prototyping.
Deep understanding of responsive grid systems, typography hierarchy, and accessibility.
Ability to articulate design trade-offs with clarity to cross-functional teams.', 'Creative autonomy on flagship international client platforms.
Close collaboration with engineering to ensure 100% design fidelity in production.
Modern equipment setup and Figma organization sponsorship.', '2026-12-31', 'PUBLISHED', '2026-10-02T06:14:11.304Z', '2026-10-02T06:14:11.304Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO jobs (id, title, department, employment_type, workplace_type, location, experience_level, salary_range, featured, skills, summary, about_role, responsibilities, requirements, benefits, deadline, status, created_at, updated_at) VALUES ('performance-marketer-lead', 'Senior Performance Marketer', 'Digital Marketing', 'Full-time', 'In-Studio', 'Hyderabad', '3–5 Years', '₹7,00,000 – ₹12,00,000 / year', FALSE, 'Meta Ads Manager, Google Ads, GA4, Funnel CRO, Attribution', 'Drive exponential customer acquisition through disciplined media buying, paid search optimization, and rigorous funnel experimentation.', 'Lead digital marketing initiatives for rapid-growth businesses. You will manage active advertising budgets, optimize full-funnel conversions, and scale customer acquisition.', 'Plan, execute, and scale high-ROI paid campaigns across Meta Ads, Google Ads, and YouTube.
Analyze attribution funnels in GA4, adjust bidding algorithms, and reduce blended CAC.
Collaborate with content creators to script high-converting video and image ad creatives.
Deliver transparent weekly ROAS, CPM, and CPA reports to client stakeholders.', 'Proven track record managing performance ad budgets with verified ROAS gains.
Expert understanding of pixel setup, server-side CAPI tracking, and GA4 telemetry.
Analytical mindset with ability to dissect marketing funnel drops and CRO bottlenecks.', 'Direct profit-sharing / performance bonus incentives tied to campaign growth.
Freedom to experiment with modern automation and creative angle testing.', '2026-12-31', 'PUBLISHED', '2026-10-02T06:14:11.304Z', '2026-10-02T06:14:11.304Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO jobs (id, title, department, employment_type, workplace_type, location, experience_level, salary_range, featured, skills, summary, about_role, responsibilities, requirements, benefits, deadline, status, created_at, updated_at) VALUES ('ai-automation-engineer', 'AI & Automation Solutions Engineer', 'AI & Automation', 'Full-time', 'Remote', 'Remote (India)', '1–3 Years', '₹7,50,000 – ₹13,00,000 / year', TRUE, 'Python, FastAPI, OpenAI API, LangChain, Web Scraping, n8n', 'Build autonomous business workflows, intelligent customer communication agents, and LLM-powered backend processing pipelines.', 'Help businesses automate manual operational friction. You will build intelligent workflow agents, API bridges, and LLM pipelines that save hundreds of labor hours.', 'Develop custom automated pipelines connecting CRM, databases, and third-party APIs.
Implement retrieval-augmented generation (RAG) and semantic search microservices in Python.
Deploy asynchronous webhook listeners, queue workers, and data extraction bots.
Maintain high system uptime, logging, and error failover mechanisms.', 'Strong proficiency in Python, RESTful API consumption, and asynchronous architecture.
Experience integrating LLM APIs, function calling, and vector embeddings.
Familiarity with cloud functions, serverless environments, and automated testing.', 'Frontier work on modern AI deployment patterns.
100% remote flexibility with asynchronous communication culture.
Continuous credits for AI research tooling and API experiments.', '2026-12-31', 'PUBLISHED', '2026-10-02T06:14:11.304Z', '2026-10-02T06:14:11.304Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO jobs (id, title, department, employment_type, workplace_type, location, experience_level, salary_range, featured, skills, summary, about_role, responsibilities, requirements, benefits, deadline, status, created_at, updated_at) VALUES ('intern-frontend-engineer', 'Associate Frontend Developer Intern', 'Internship', 'Internship (3–6 Months)', 'Hybrid', 'Hyderabad', 'Students / Recent Graduates', 'Stipend + Placement Assistance', FALSE, 'JavaScript, React Basics, HTML5, CSS3, Git', 'Launch your engineering career with direct apprenticeship on live codebases, structured mentor feedback, and verified studio contribution credentials.', 'Designed for high-potential students and recent graduates seeking real-world software engineering apprenticeship. You will ship real code to production under senior oversight.', 'Implement UI components following clean code standards in React.
Fix responsive layout bugs across modern mobile and desktop browsers.
Participate in daily standups and learn professional Git branching conventions.', 'Foundational knowledge of JavaScript, modern ES6 syntax, and web fundamentals.
Completed personal or academic web projects that demonstrate initiative.
Eagerness to learn, accept constructive code reviews, and ship iteratively.', 'Hands-on experience with production codebases (zero toy todo apps).
Direct 1-on-1 mentorship from seasoned engineering leads.
Full placement assistance and immediate consideration for permanent full-time hiring.', '2026-12-31', 'PUBLISHED', '2026-10-02T06:14:11.304Z', '2026-10-02T06:14:11.304Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO jobs (id, title, department, employment_type, workplace_type, location, experience_level, salary_range, featured, skills, summary, about_role, responsibilities, requirements, benefits, deadline, status, created_at, updated_at) VALUES ('lead-devops-architect-kubernetes-aws-muqktwvx', 'Lead DevOps Architect (Kubernetes & AWS)', 'Software Development', 'Full-time', 'Hybrid', 'Hyderabad, India', '4–7 Years', '₹14,00,000 – ₹22,00,000 / year', FALSE, '', 'Lead scalable multi-region cloud deployment and CI/CD pipelines.', '', '', '', '', '', 'ARCHIVED', '2026-10-02T06:23:08.734Z', '2026-10-02T06:23:08.775Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO jobs (id, title, department, employment_type, workplace_type, location, experience_level, salary_range, featured, skills, summary, about_role, responsibilities, requirements, benefits, deadline, status, created_at, updated_at) VALUES ('lead-devops-architect-kubernetes-aws-muqmcbfm', 'Lead DevOps Architect (Kubernetes & AWS)', 'Software Development', 'Full-time', 'Hybrid', 'Hyderabad, India', '4–7 Years', '₹14,00,000 – ₹22,00,000 / year', FALSE, '', 'Lead scalable multi-region cloud deployment and CI/CD pipelines.', '', '', '', '', '', 'ARCHIVED', '2026-10-02T07:05:27.011Z', '2026-10-02T07:05:27.085Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO jobs (id, title, department, employment_type, workplace_type, location, experience_level, salary_range, featured, skills, summary, about_role, responsibilities, requirements, benefits, deadline, status, created_at, updated_at) VALUES ('lead-devops-architect-kubernetes-aws-muqupfg7', 'Lead DevOps Architect (Kubernetes & AWS)', 'Software Development', 'Full-time', 'Hybrid', 'Hyderabad, India', '4–7 Years', '₹14,00,000 – ₹22,00,000 / year', FALSE, '', 'Lead scalable multi-region cloud deployment and CI/CD pipelines.', '', '', '', '', '', 'ARCHIVED', '2026-10-02T10:59:35.671Z', '2026-10-02T10:59:35.754Z') ON CONFLICT (id) DO NOTHING;

-- 4. APPLICATIONS
INSERT INTO applications (id, candidate_id, job_id, job_title, department, applicant_name, applicant_email, applicant_phone, location, college, education, graduation_year, skills, years_experience, linkedin_url, github_url, portfolio_url, cover_letter, resume_storage_path, resume_filename, status, admin_notes, status_history, created_at, updated_at) VALUES ('app_1790919940318_hcpb', 'usr_1790919940279_ijgx5', 'fullstack-engineer-01', 'Senior Full Stack Engineer', 'Technology', '', '', '', '', '', '', '', '[]'::jsonb, '', '', '', '', '', 'C:\Users\bantu\Desktop\KWT\backend\uploads\resumes\resume_Harsha_Resume_2026_1790919940303-386237.pdf', 'Harsha_Resume_2026.pdf', 'SHORTLISTED', '', '[]'::jsonb, '2026-10-02T05:45:40.319Z', '2026-10-02T05:45:40.464Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO applications (id, candidate_id, job_id, job_title, department, applicant_name, applicant_email, applicant_phone, location, college, education, graduation_year, skills, years_experience, linkedin_url, github_url, portfolio_url, cover_letter, resume_storage_path, resume_filename, status, admin_notes, status_history, created_at, updated_at) VALUES ('app_1790919954894_az5x', 'usr_1790919954871_2obaz', 'fullstack-engineer-01', 'Senior Full Stack Engineer', 'Technology', '', '', '', '', '', '', '', '[]'::jsonb, '', '', '', '', '', 'C:\Users\bantu\Desktop\KWT\backend\uploads\resumes\resume_Harsha_Resume_2026_1790919954886-714571.pdf', 'Harsha_Resume_2026.pdf', 'SHORTLISTED', '', '[]'::jsonb, '2026-10-02T05:45:54.895Z', '2026-10-02T05:45:55.065Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO applications (id, candidate_id, job_id, job_title, department, applicant_name, applicant_email, applicant_phone, location, college, education, graduation_year, skills, years_experience, linkedin_url, github_url, portfolio_url, cover_letter, resume_storage_path, resume_filename, status, admin_notes, status_history, created_at, updated_at) VALUES ('app_1790922188745_gvi0', 'usr_1790922188633_9si1j', 'lead-devops-architect-kubernetes-aws-muqktwvx', 'Lead DevOps Architect (Kubernetes & AWS)', 'Technology', '', '', '', '', '', '', '', '[]'::jsonb, '', '', '', '', '', '', 'Ananya_Sharma_Application_Profile.pdf', 'SHORTLISTED', 'Candidate demonstrates strong Kubernetes and Terraform knowledge. Proceed to technical round.', '[{"status":"SHORTLISTED","updated_by":"admin@kodewar.com","updated_at":"2026-10-02T06:23:08.760Z","notes":"Candidate demonstrates strong Kubernetes and Terraform knowledge. Proceed to technical round."}]'::jsonb, '2026-10-02T06:23:08.746Z', '2026-10-02T06:23:08.761Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO applications (id, candidate_id, job_id, job_title, department, applicant_name, applicant_email, applicant_phone, location, college, education, graduation_year, skills, years_experience, linkedin_url, github_url, portfolio_url, cover_letter, resume_storage_path, resume_filename, status, admin_notes, status_history, created_at, updated_at) VALUES ('app_1790924727039_9x7d', 'usr_1790924726791_bswno', 'lead-devops-architect-kubernetes-aws-muqmcbfm', 'Lead DevOps Architect (Kubernetes & AWS)', 'Technology', '', '', '', '', '', '', '', '[]'::jsonb, '', '', '', '', '', '', 'Ananya_Sharma_Application_Profile.pdf', 'SHORTLISTED', 'Candidate demonstrates strong Kubernetes and Terraform knowledge. Proceed to technical round.', '[{"status":"SHORTLISTED","updated_by":"admin@kodewar.com","updated_at":"2026-10-02T07:05:27.062Z","notes":"Candidate demonstrates strong Kubernetes and Terraform knowledge. Proceed to technical round."}]'::jsonb, '2026-10-02T07:05:27.039Z', '2026-10-02T07:05:27.063Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO applications (id, candidate_id, job_id, job_title, department, applicant_name, applicant_email, applicant_phone, location, college, education, graduation_year, skills, years_experience, linkedin_url, github_url, portfolio_url, cover_letter, resume_storage_path, resume_filename, status, admin_notes, status_history, created_at, updated_at) VALUES ('app_1790924871549_zihv', 'usr_1790924871492_420yo', 'fullstack-engineer-01', 'Senior Full Stack Engineer', 'Technology', '', '', '', '', '', '', '', '[]'::jsonb, '', '', '', '', '', 'C:\Users\bantu\Desktop\KWT\backend\uploads\resumes\resume_Harsha_Resume_2026_1790924871531-243499.pdf', 'Harsha_Resume_2026.pdf', 'SHORTLISTED', '', '[{"status":"SHORTLISTED","updated_by":"admin@kodewar.com","updated_at":"2026-10-02T07:07:51.811Z","notes":""}]'::jsonb, '2026-10-02T07:07:51.549Z', '2026-10-02T07:07:51.813Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO applications (id, candidate_id, job_id, job_title, department, applicant_name, applicant_email, applicant_phone, location, college, education, graduation_year, skills, years_experience, linkedin_url, github_url, portfolio_url, cover_letter, resume_storage_path, resume_filename, status, admin_notes, status_history, created_at, updated_at) VALUES ('app_1790938775703_w8o6', 'usr_1790938775308_dsjtp', 'lead-devops-architect-kubernetes-aws-muqupfg7', 'Lead DevOps Architect (Kubernetes & AWS)', 'Technology', '', '', '', '', '', '', '', '[]'::jsonb, '', '', '', '', '', '', 'Ananya_Sharma_Application_Profile.pdf', 'SHORTLISTED', 'Candidate demonstrates strong Kubernetes and Terraform knowledge. Proceed to technical round.', '[{"status":"SHORTLISTED","updated_by":"admin@kodewar.com","updated_at":"2026-10-02T10:59:35.729Z","notes":"Candidate demonstrates strong Kubernetes and Terraform knowledge. Proceed to technical round."}]'::jsonb, '2026-10-02T10:59:35.704Z', '2026-10-02T10:59:35.729Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO applications (id, candidate_id, job_id, job_title, department, applicant_name, applicant_email, applicant_phone, location, college, education, graduation_year, skills, years_experience, linkedin_url, github_url, portfolio_url, cover_letter, resume_storage_path, resume_filename, status, admin_notes, status_history, created_at, updated_at) VALUES ('app_1790938792472_vv6x', 'usr_1790938792342_cnrug', 'fullstack-engineer-01', 'Senior Full Stack Engineer', 'Technology', '', '', '', '', '', '', '', '[]'::jsonb, '', '', '', '', '', 'C:\Users\bantu\Desktop\KWT\backend\uploads\resumes\resume_Harsha_Resume_2026_1790938792396-678722.pdf', 'Harsha_Resume_2026.pdf', 'SHORTLISTED', '', '[{"status":"SHORTLISTED","updated_by":"admin@kodewar.com","updated_at":"2026-10-02T10:59:52.769Z","notes":""}]'::jsonb, '2026-10-02T10:59:52.473Z', '2026-10-02T10:59:52.769Z') ON CONFLICT (id) DO NOTHING;

-- 5. TRAINING PROGRAMS
INSERT INTO training_programs (id, name, description, duration, mode, skills, eligibility, instructions, highlights, status, created_at, updated_at) VALUES ('fullstack-dev', 'Full Stack Development', 'An industry-oriented curriculum where candidates build production-level software using React, Next.js, Node.js, and relational databases under senior practitioner oversight.', '12 Weeks (Immersive)', 'In-Studio (Hyderabad) / Hybrid', 'React & Next.js, Node.js & Express, PostgreSQL / MySQL, REST APIs, Git Flow & CI/CD, Docker Basics', 'Final year engineering students, recent graduates, or aspiring developers with basic programming fundamentals seeking practical career preparation.', 'Submit your candidate application through the KODEWAR Careers portal. Shortlisted applicants will be invited for a diagnostic technical conversation.', '100% production codebases, zero toy todo apps
Daily standups, peer code reviews, and Git collaboration
Comprehensive placement assistance & portfolio audit
Direct consideration for open KODEWAR engineering roles', 'PUBLISHED', '2026-10-02T06:14:11.305Z', '2026-10-02T06:14:11.305Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO training_programs (id, name, description, duration, mode, skills, eligibility, instructions, highlights, status, created_at, updated_at) VALUES ('ui-ux-design', 'UI/UX Product Design', 'Master digital product design through real design sprints, wireframing, component design tokens, and user testing. Graduate with a production-ready portfolio case study.', '10 Weeks', 'In-Studio / Remote', 'Figma Mastery, Design Tokens & Systems, User Research & Wireframing, Interactive Prototyping, Developer Handoff, Heuristic Audits', 'Creative problem-solvers, graphic designers transitioning to product UI/UX, and students passionate about digital interfaces.', 'Apply with links to any existing sketches, visual projects, or design work. Prior tool experience in Figma is helpful but not mandatory.', 'Build 3 comprehensive, verified portfolio case studies
Learn how to collaborate with frontend engineers
Mentorship from practicing UI/UX product leads
Placement assistance and resume refinement', 'PUBLISHED', '2026-10-02T06:14:11.305Z', '2026-10-02T06:14:11.305Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO training_programs (id, name, description, duration, mode, skills, eligibility, instructions, highlights, status, created_at, updated_at) VALUES ('digital-marketing', 'Digital Marketing & Growth', 'Learn performance marketing by managing live ad budgets, analyzing GA4 telemetry, conducting funnel CRO, and scripting high-conversion creative hooks.', '8 Weeks', 'In-Studio / Hybrid', 'Meta Ads Manager, Google Ads & Search, GA4 & Tag Manager, Funnel CRO, Ad Copywriting, Short-form Video Strategy', 'Marketing graduates, founders, and career switchers wanting practical paid media experience without academic fluff.', 'Complete the candidate registration and submit your background interest. Live ad account access is provided during cohort sessions.', 'Hands-on experience with live ad spend budgets
Data-driven performance attribution telemetry
Industry-oriented training with agency practitioners
Placement assistance with active commercial partners', 'PUBLISHED', '2026-10-02T06:14:11.305Z', '2026-10-02T06:14:11.305Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO training_programs (id, name, description, duration, mode, skills, eligibility, instructions, highlights, status, created_at, updated_at) VALUES ('ai-automation', 'AI & Automation Engineering', 'Bridge software engineering and artificial intelligence. Build automated workflow agents, data ingestion pipelines, and LLM-powered backend tools.', '10 Weeks', 'In-Studio / Remote', 'Python Fundamentals, FastAPI Microservices, Web Scraping & Crawling, Agentic Automations, LLM API Integrations, Task Queues & Webhooks', 'Developers and engineering students with Python basics looking to specialize in high-demand automation and AI infrastructure.', 'Submit your profile along with your GitHub profile or code samples. Basic understanding of loops, functions, and HTTP APIs is recommended.', 'Deploy real agentic workflows and ETL pipelines
Learn asynchronous architecture and web crawling
Practical projects showcasing verifiable AI utility
Career preparation and technical interview coaching', 'PUBLISHED', '2026-10-02T06:14:11.305Z', '2026-10-02T06:14:11.305Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO training_programs (id, name, description, duration, mode, skills, eligibility, instructions, highlights, status, created_at, updated_at) VALUES ('cloud-devops-sre-apprenticeship-muqkrium', 'Cloud DevOps & SRE Apprenticeship', 'Immersive infrastructure engineering on Kubernetes, AWS, and Terraform.', '12 Weeks', 'Hybrid', 'Kubernetes, Docker, AWS, CI/CD, Prometheus', '', 'Submit your candidate application through the KODEWAR Careers portal.', '', 'PUBLISHED', '2026-10-02T06:21:17.230Z', '2026-10-02T06:21:17.230Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO training_programs (id, name, description, duration, mode, skills, eligibility, instructions, highlights, status, created_at, updated_at) VALUES ('cloud-devops-sre-apprenticeship-muqktwx6', 'Cloud DevOps & SRE Apprenticeship', 'Immersive infrastructure engineering on Kubernetes, AWS, and Terraform.', '12 Weeks', 'Hybrid', 'Kubernetes, Docker, AWS, CI/CD, Prometheus', '', 'Submit your candidate application through the KODEWAR Careers portal.', '', 'PUBLISHED', '2026-10-02T06:23:08.779Z', '2026-10-02T06:23:08.779Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO training_programs (id, name, description, duration, mode, skills, eligibility, instructions, highlights, status, created_at, updated_at) VALUES ('cloud-devops-sre-apprenticeship-muqmcbhu', 'Cloud DevOps & SRE Apprenticeship', 'Immersive infrastructure engineering on Kubernetes, AWS, and Terraform.', '12 Weeks', 'Hybrid', 'Kubernetes, Docker, AWS, CI/CD, Prometheus', '', 'Submit your candidate application through the KODEWAR Careers portal.', '', 'PUBLISHED', '2026-10-02T07:05:27.091Z', '2026-10-02T07:05:27.091Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO training_programs (id, name, description, duration, mode, skills, eligibility, instructions, highlights, status, created_at, updated_at) VALUES ('cloud-devops-sre-apprenticeship-muqupfip', 'Cloud DevOps & SRE Apprenticeship', 'Immersive infrastructure engineering on Kubernetes, AWS, and Terraform.', '12 Weeks', 'Hybrid', 'Kubernetes, Docker, AWS, CI/CD, Prometheus', '', 'Submit your candidate application through the KODEWAR Careers portal.', '', 'PUBLISHED', '2026-10-02T10:59:35.762Z', '2026-10-02T10:59:35.762Z') ON CONFLICT (id) DO NOTHING;

-- 6. TESTIMONIALS
INSERT INTO testimonials (id, name, role, program, cohort, quote, image_url, status, created_at, updated_at) VALUES ('test-1', 'Surya Narayana', 'Full Stack Engineer at KODEWAR', 'Engineering Apprenticeship', 'Cohort 2025 // Hyderabad', 'Joining KODEWAR as an apprentice changed my entire trajectory. Rather than building dummy projects, I was given responsibility on live platforms from week three. The code reviews made me think like a senior architect.', '/team/profile1.png', 'PUBLISHED', '2026-10-02T06:14:11.306Z', '2026-10-02T06:14:11.306Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO testimonials (id, name, role, program, cohort, quote, image_url, status, created_at, updated_at) VALUES ('test-2', 'Aareefa Begum', 'Frontend Developer', 'Product Engineering Track', 'Frontend Track // 2025', 'The emphasis on design fidelity and animation performance at KODEWAR is completely unmatched. You learn how to convert complex Figma design tokens into clean React components that ship to production.', '/team/profile2.png', 'PUBLISHED', '2026-10-02T06:14:11.306Z', '2026-10-02T06:14:11.306Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO testimonials (id, name, role, program, cohort, quote, image_url, status, created_at, updated_at) VALUES ('test-3', 'Kiran Kumar', 'MERN Stack Developer', 'Backend & Cloud Apprenticeship', 'Backend & Cloud // 2025', 'The placement assistance and technical interview coaching were instrumental. The mentors don’t just teach syntax—they teach how production systems scale under real-world traffic.', '/team/profile3.png', 'PUBLISHED', '2026-10-02T06:14:11.306Z', '2026-10-02T06:14:11.306Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO testimonials (id, name, role, program, cohort, quote, image_url, status, created_at, updated_at) VALUES ('test-muqkriuu', 'Sravani Rao', 'DevOps Engineer at CloudWorks', 'Cloud Apprenticeship // 2025', '', 'KODEWAR gave me real cluster access from day one. I learned more in 3 months than in 4 years of college.', '', 'PUBLISHED', '2026-10-02T06:21:17.239Z', '2026-10-02T06:21:17.239Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO testimonials (id, name, role, program, cohort, quote, image_url, status, created_at, updated_at) VALUES ('test-muqktwxc', 'Sravani Rao', 'DevOps Engineer at CloudWorks', 'Cloud Apprenticeship // 2025', '', 'KODEWAR gave me real cluster access from day one. I learned more in 3 months than in 4 years of college.', '', 'PUBLISHED', '2026-10-02T06:23:08.784Z', '2026-10-02T06:23:08.784Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO testimonials (id, name, role, program, cohort, quote, image_url, status, created_at, updated_at) VALUES ('test-muqmcbi5', 'Sravani Rao', 'DevOps Engineer at CloudWorks', 'Cloud Apprenticeship // 2025', '', 'KODEWAR gave me real cluster access from day one. I learned more in 3 months than in 4 years of college.', '', 'PUBLISHED', '2026-10-02T07:05:27.101Z', '2026-10-02T07:05:27.101Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO testimonials (id, name, role, program, cohort, quote, image_url, status, created_at, updated_at) VALUES ('test-muqupfj2', 'Sravani Rao', 'DevOps Engineer at CloudWorks', 'Cloud Apprenticeship // 2025', '', 'KODEWAR gave me real cluster access from day one. I learned more in 3 months than in 4 years of college.', '', 'PUBLISHED', '2026-10-02T10:59:35.774Z', '2026-10-02T10:59:35.774Z') ON CONFLICT (id) DO NOTHING;

COMMIT;