export const INITIAL_SEED_JOBS = [
  {
    id: 'frontend-engineer-react',
    title: 'Frontend Engineer (React / Next.js)',
    department: 'Software Development',
    employment_type: 'Full-time',
    workplace_type: 'Hybrid',
    location: 'Hyderabad / Remote',
    experience_level: '1–3 Years',
    salary_range: '₹6,00,000 – ₹10,00,000 / year',
    featured: true,
    skills: 'React, Next.js, TypeScript, Tailwind CSS, GSAP',
    summary: 'Architect high-performance web applications, fluid micro-interactions, and enterprise design systems with sub-second page performance.',
    about_role: 'As a Frontend Engineer at KODEWAR, you will build user-facing platforms for global clients and internal products. You will work closely with product designers to translate Figma design tokens into clean, performant React components.',
    responsibilities: 'Build responsive, production-ready user interfaces using React, Next.js, and TypeScript.\nImplement fluid animations and micro-interactions utilizing GSAP and CSS transforms.\nCollaborate with UI/UX designers to translate Figma tokens into scalable component libraries.\nOptimize web applications for peak Core Web Vitals and accessibility standards.',
    requirements: 'Proficiency in React, modern JavaScript (ES6+), and CSS/Tailwind.\nExperience with state management, asynchronous data fetching, and RESTful APIs.\nStrong eye for spacing, typography, and micro-interactions.\nPortfolio or GitHub repositories demonstrating real deployed projects.',
    benefits: 'Work on live production platforms across multiple continents.\nDirect 1-on-1 code reviews and architectural mentorship.\nHigh-velocity shipping culture without bureaucratic friction.\nContinuous hardware and learning stipend support.',
    deadline: '2026-12-31',
    status: 'PUBLISHED',
  },
  {
    id: 'fullstack-developer-mern',
    title: 'Full Stack Developer (Node.js & React)',
    department: 'Software Development',
    employment_type: 'Full-time',
    workplace_type: 'In-Studio',
    location: 'Hyderabad',
    experience_level: '2–4 Years',
    salary_range: '₹8,00,000 – ₹14,00,000 / year',
    featured: true,
    skills: 'Node.js, Express, React, PostgreSQL, REST APIs',
    summary: 'Lead end-to-end development of client-facing platforms, secure API microservices, and robust relational data pipelines.',
    about_role: 'Join our core platform engineering team in Madhapur, Hyderabad. You will architect resilient backend services, design optimized database schemas, and deliver polished web interfaces.',
    responsibilities: 'Design, develop, and maintain resilient Node.js / Express microservices and REST APIs.\nArchitect relational database schemas in PostgreSQL / MySQL with optimized indexing.\nIntegrate third-party payment gateways, authentication providers, and webhooks.\nParticipate in agile sprint ceremonies, peer code reviews, and architecture spikes.',
    requirements: 'Demonstrated experience building and maintaining full-stack web applications.\nStrong grasp of backend architectural patterns, JWT authentication, and database modeling.\nFamiliarity with containerization (Docker) and cloud deployments.',
    benefits: 'Direct ownership of entire product features from inception to deployment.\nCollaborative engineering squad alongside experienced leads.\nMerit-driven compensation and accelerated career progression.\nStudio workplace in Madhapur, Hyderabad with hybrid flexibility.',
    deadline: '2026-12-31',
    status: 'PUBLISHED',
  },
  {
    id: 'ui-ux-product-designer',
    title: 'UI/UX Product Designer',
    department: 'UI/UX & Design',
    employment_type: 'Full-time',
    workplace_type: 'Hybrid',
    location: 'Hyderabad / Remote',
    experience_level: '2–4 Years',
    salary_range: '₹6,50,000 – ₹11,00,000 / year',
    featured: true,
    skills: 'Figma, Design Systems, Wireframing, UX Research, Micro-interactions',
    summary: 'Craft high-conversion product interfaces, interactive design tokens, and user research archetypes for complex digital ecosystems.',
    about_role: 'Work at the intersection of aesthetic craft and usability. You will lead interface architecture across web, mobile, and SaaS dashboards.',
    responsibilities: 'Translate ambiguous client requirements into clear wireframes, user journeys, and mockups.\nMaintain and evolve the KODEWAR design system and component tokens in Figma.\nConduct usability audits, prototype micro-interactions, and hand off specifications to frontend engineers.\nIterate based on qualitative client feedback and quantitative product telemetry.',
    requirements: 'High-caliber portfolio showcasing shipped web apps, mobile apps, or design systems.\nMastery of Figma, Auto-layout, component variants, and interactive prototyping.\nDeep understanding of responsive grid systems, typography hierarchy, and accessibility.\nAbility to articulate design trade-offs with clarity to cross-functional teams.',
    benefits: 'Creative autonomy on flagship international client platforms.\nClose collaboration with engineering to ensure 100% design fidelity in production.\nModern equipment setup and Figma organization sponsorship.',
    deadline: '2026-12-31',
    status: 'PUBLISHED',
  },
  {
    id: 'performance-marketer-lead',
    title: 'Senior Performance Marketer',
    department: 'Digital Marketing',
    employment_type: 'Full-time',
    workplace_type: 'In-Studio',
    location: 'Hyderabad',
    experience_level: '3–5 Years',
    salary_range: '₹7,00,000 – ₹12,00,000 / year',
    featured: false,
    skills: 'Meta Ads Manager, Google Ads, GA4, Funnel CRO, Attribution',
    summary: 'Drive exponential customer acquisition through disciplined media buying, paid search optimization, and rigorous funnel experimentation.',
    about_role: 'Lead digital marketing initiatives for rapid-growth businesses. You will manage active advertising budgets, optimize full-funnel conversions, and scale customer acquisition.',
    responsibilities: 'Plan, execute, and scale high-ROI paid campaigns across Meta Ads, Google Ads, and YouTube.\nAnalyze attribution funnels in GA4, adjust bidding algorithms, and reduce blended CAC.\nCollaborate with content creators to script high-converting video and image ad creatives.\nDeliver transparent weekly ROAS, CPM, and CPA reports to client stakeholders.',
    requirements: 'Proven track record managing performance ad budgets with verified ROAS gains.\nExpert understanding of pixel setup, server-side CAPI tracking, and GA4 telemetry.\nAnalytical mindset with ability to dissect marketing funnel drops and CRO bottlenecks.',
    benefits: 'Direct profit-sharing / performance bonus incentives tied to campaign growth.\nFreedom to experiment with modern automation and creative angle testing.',
    deadline: '2026-12-31',
    status: 'PUBLISHED',
  },
  {
    id: 'ai-automation-engineer',
    title: 'AI & Automation Solutions Engineer',
    department: 'AI & Automation',
    employment_type: 'Full-time',
    workplace_type: 'Remote',
    location: 'Remote (India)',
    experience_level: '1–3 Years',
    salary_range: '₹7,50,000 – ₹13,00,000 / year',
    featured: true,
    skills: 'Python, FastAPI, OpenAI API, LangChain, Web Scraping, n8n',
    summary: 'Build autonomous business workflows, intelligent customer communication agents, and LLM-powered backend processing pipelines.',
    about_role: 'Help businesses automate manual operational friction. You will build intelligent workflow agents, API bridges, and LLM pipelines that save hundreds of labor hours.',
    responsibilities: 'Develop custom automated pipelines connecting CRM, databases, and third-party APIs.\nImplement retrieval-augmented generation (RAG) and semantic search microservices in Python.\nDeploy asynchronous webhook listeners, queue workers, and data extraction bots.\nMaintain high system uptime, logging, and error failover mechanisms.',
    requirements: 'Strong proficiency in Python, RESTful API consumption, and asynchronous architecture.\nExperience integrating LLM APIs, function calling, and vector embeddings.\nFamiliarity with cloud functions, serverless environments, and automated testing.',
    benefits: 'Frontier work on modern AI deployment patterns.\n100% remote flexibility with asynchronous communication culture.\nContinuous credits for AI research tooling and API experiments.',
    deadline: '2026-12-31',
    status: 'PUBLISHED',
  },
  {
    id: 'intern-frontend-engineer',
    title: 'Associate Frontend Developer Intern',
    department: 'Internship',
    employment_type: 'Internship (3–6 Months)',
    workplace_type: 'Hybrid',
    location: 'Hyderabad',
    experience_level: 'Students / Recent Graduates',
    salary_range: 'Stipend + Placement Assistance',
    featured: false,
    skills: 'JavaScript, React Basics, HTML5, CSS3, Git',
    summary: 'Launch your engineering career with direct apprenticeship on live codebases, structured mentor feedback, and verified studio contribution credentials.',
    about_role: 'Designed for high-potential students and recent graduates seeking real-world software engineering apprenticeship. You will ship real code to production under senior oversight.',
    responsibilities: 'Implement UI components following clean code standards in React.\nFix responsive layout bugs across modern mobile and desktop browsers.\nParticipate in daily standups and learn professional Git branching conventions.',
    requirements: 'Foundational knowledge of JavaScript, modern ES6 syntax, and web fundamentals.\nCompleted personal or academic web projects that demonstrate initiative.\nEagerness to learn, accept constructive code reviews, and ship iteratively.',
    benefits: 'Hands-on experience with production codebases (zero toy todo apps).\nDirect 1-on-1 mentorship from seasoned engineering leads.\nFull placement assistance and immediate consideration for permanent full-time hiring.',
    deadline: '2026-12-31',
    status: 'PUBLISHED',
  },
];

export const INITIAL_SEED_TRAINING = [
  {
    id: 'fullstack-dev',
    name: 'Full Stack Development',
    duration: '12 Weeks (Immersive)',
    mode: 'In-Studio (Hyderabad) / Hybrid',
    badge: 'ENGINEERING APPRENTICESHIP',
    description: 'An industry-oriented curriculum where candidates build production-level software using React, Next.js, Node.js, and relational databases under senior practitioner oversight.',
    skills: 'React & Next.js, Node.js & Express, PostgreSQL / MySQL, REST APIs, Git Flow & CI/CD, Docker Basics',
    eligibility: 'Final year engineering students, recent graduates, or aspiring developers with basic programming fundamentals seeking practical career preparation.',
    instructions: 'Submit your candidate application through the KODEWAR Careers portal. Shortlisted applicants will be invited for a diagnostic technical conversation.',
    highlights: '100% production codebases, zero toy todo apps\nDaily standups, peer code reviews, and Git collaboration\nComprehensive placement assistance & portfolio audit\nDirect consideration for open KODEWAR engineering roles',
    status: 'PUBLISHED',
  },
  {
    id: 'ui-ux-design',
    name: 'UI/UX Product Design',
    duration: '10 Weeks',
    mode: 'In-Studio / Remote',
    badge: 'PRODUCT CRAFT',
    description: 'Master digital product design through real design sprints, wireframing, component design tokens, and user testing. Graduate with a production-ready portfolio case study.',
    skills: 'Figma Mastery, Design Tokens & Systems, User Research & Wireframing, Interactive Prototyping, Developer Handoff, Heuristic Audits',
    eligibility: 'Creative problem-solvers, graphic designers transitioning to product UI/UX, and students passionate about digital interfaces.',
    instructions: 'Apply with links to any existing sketches, visual projects, or design work. Prior tool experience in Figma is helpful but not mandatory.',
    highlights: 'Build 3 comprehensive, verified portfolio case studies\nLearn how to collaborate with frontend engineers\nMentorship from practicing UI/UX product leads\nPlacement assistance and resume refinement',
    status: 'PUBLISHED',
  },
  {
    id: 'digital-marketing',
    name: 'Digital Marketing & Growth',
    duration: '8 Weeks',
    mode: 'In-Studio / Hybrid',
    badge: 'COMMERCIAL LEVERAGE',
    description: 'Learn performance marketing by managing live ad budgets, analyzing GA4 telemetry, conducting funnel CRO, and scripting high-conversion creative hooks.',
    skills: 'Meta Ads Manager, Google Ads & Search, GA4 & Tag Manager, Funnel CRO, Ad Copywriting, Short-form Video Strategy',
    eligibility: 'Marketing graduates, founders, and career switchers wanting practical paid media experience without academic fluff.',
    instructions: 'Complete the candidate registration and submit your background interest. Live ad account access is provided during cohort sessions.',
    highlights: 'Hands-on experience with live ad spend budgets\nData-driven performance attribution telemetry\nIndustry-oriented training with agency practitioners\nPlacement assistance with active commercial partners',
    status: 'PUBLISHED',
  },
  {
    id: 'ai-automation',
    name: 'AI & Automation Engineering',
    duration: '10 Weeks',
    mode: 'In-Studio / Remote',
    badge: 'NEXT-GEN TOOLING',
    description: 'Bridge software engineering and artificial intelligence. Build automated workflow agents, data ingestion pipelines, and LLM-powered backend tools.',
    skills: 'Python Fundamentals, FastAPI Microservices, Web Scraping & Crawling, Agentic Automations, LLM API Integrations, Task Queues & Webhooks',
    eligibility: 'Developers and engineering students with Python basics looking to specialize in high-demand automation and AI infrastructure.',
    instructions: 'Submit your profile along with your GitHub profile or code samples. Basic understanding of loops, functions, and HTTP APIs is recommended.',
    highlights: 'Deploy real agentic workflows and ETL pipelines\nLearn asynchronous architecture and web crawling\nPractical projects showcasing verifiable AI utility\nCareer preparation and technical interview coaching',
    status: 'PUBLISHED',
  },
];

export const INITIAL_SEED_TESTIMONIALS = [
  {
    id: 'test-1',
    name: 'Surya Narayana',
    role: 'Full Stack Engineer at KODEWAR',
    program: 'Engineering Apprenticeship',
    cohort: 'Cohort 2025 // Hyderabad',
    quote: 'Joining KODEWAR as an apprentice changed my entire trajectory. Rather than building dummy projects, I was given responsibility on live platforms from week three. The code reviews made me think like a senior architect.',
    image_url: '/team/profile1.png',
    status: 'PUBLISHED',
  },
  {
    id: 'test-2',
    name: 'Aareefa Begum',
    role: 'Frontend Developer',
    program: 'Product Engineering Track',
    cohort: 'Frontend Track // 2025',
    quote: 'The emphasis on design fidelity and animation performance at KODEWAR is completely unmatched. You learn how to convert complex Figma design tokens into clean React components that ship to production.',
    image_url: '/team/profile2.png',
    status: 'PUBLISHED',
  },
  {
    id: 'test-3',
    name: 'Kiran Kumar',
    role: 'MERN Stack Developer',
    program: 'Backend & Cloud Apprenticeship',
    cohort: 'Backend & Cloud // 2025',
    quote: 'The placement assistance and technical interview coaching were instrumental. The mentors don’t just teach syntax—they teach how production systems scale under real-world traffic.',
    image_url: '/team/profile3.png',
    status: 'PUBLISHED',
  },
];
